language: node_js
node_js:
- '7'
notifications:
  email: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- sleep 1
before_script:
- npm rebuild phantomjs-prebuilt node-sass
- sleep 1
script:
- npm run lint
- npm run test:ci
before_deploy:
- npm install -g firebase-tools
- echo 'About to deploy live...'
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
    tags: true
  token:
    secure: aFSRYIrEbnHWVAZe1csRsQepGDghypfk8yEAfZOExSgdThCSBMNYnSxbsJeWe8RR3oDz2fDKCSdVZ7txTO6Wkx1SQHcE1dMKdK9qhrOyFgS47/O8+rYuUcYKRt3XKV7c323pS9dNiTGcmk1CAvXojhlsDsB93o4q+1tfZM5p8F0SdvwHBPKyC/ywqn/avk3eTKhWZY9Ls58FGMzsytYWtRz42CGdrIvT2tvJSBZctrSjStc0m1Fc7+eXGX+9WLLBL7Ru26oPRh+gFx84mhAFXJPc7NuQ3q8amAWcHp92owB2TEPhMYt1DoKpQshu6RFxHJOWsumNt/Yywl0n+WF6S+Fm73/wFOLvx9hMZvOdyCTE7JUPeckVobvIwi1YDYF4Fm+OVs567B9FBRRqN5JE5s4Qpgy0Hu0liAeInTuGTtMMOq7CyMdLuuhQ5FzFb4G9XysludMnmvlZ2UE1N6MdU8CeBwostEzCo8lwmhu1yZIwuut+gglFXI9+flWhjcwmPAR6eJgB5VORmR8/Vu8c88+ThyLmg3PQESXVqKySGsxhEWn30TCHO7KNd6/JgVlDgGc4ihgnzkLXohdMnRRt2OXgGwSOZrrF/cYZ+ynSwV/FQnXrbmIkymQYKgQalV8CAa8wvq+m/oLCmmvSvU3WsrpQeD/opE1LlzjnLtSV86I=
  project: rock-paper-scissors-pwa
