language: node_js
node_js:
- '7'
notifications:
  email: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- sleep 1
before_script:
- npm rebuild phantomjs-prebuilt node-sass
- sleep 1
script:
- npm run lint
- npm run test:ci
- npm run coveralls
before_deploy:
- npm install -g firebase-tools
- echo 'About to deploy live...'
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
    tags: true
  token:
    secure: XR2+8tyBAB6zSgPlls6jBc84Ddxs1DnKypgc0c1G+oyWmA5N0ww4zJ7rkrAWjyHe9U354d3qsr4p7R/V/ua8xEMlbFGQA2sva5qe+OXaP2G1iPUYQuqcgMGITywNwllE1DSq2r1qo8IsI0rG2LidyWRVHbLjPJPbjVG6IZCB1cull6OIqqVblAox1yADdsk6CK2nO8d7PYUdF7L6Dh9dDk/rKzV7HKNi9h5L1CzCnKNebn9OTUtVgA/+HuVonK5uCth/Tcbm7ZJuA7De2q1fXNjz3g7H6pWFsMcIr/5++V7exZR+hGq+wNJ3/FbTR16yfii2h0sHqzN/hmR7D8syPfadVYqczQYC/zeMKcpSF9lealZmvPlBsX07jNBnI94EK/RB3zmHxzR/hgImxL5j3gV7B4s3B8qnSaYpM7vHjTJ1RUkB9zPtBG/s8V2SI77aEbi/JnkWAUKk7ncNPTS2hgWFOU4OwHjhNoFmImWosnxCM0OE5HpGXcsmICwo3Jd2G+G9y02i8AxDybdlrR406ywPiNoSbhrnAIqWeo3v8o2tkFP0jPxHoLK8vTVFD3SeE2XxE8afOOyzGrKdM7jBnceab6lK1RHDnZ6lsR24bZ8XlrMnQw/CK0fcMofALmdnzg7FsE1OZe61STDQdo+G8jeShBpZnVIhbNJ1XESfcKc=
  project: rock-paper-scissors-pwa
