language: node_js
node_js:
- '7'
notifications:
  email: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- sleep 1
before_script:
- npm rebuild phantomjs-prebuilt node-sass
- sleep 1
script:
- npm run lint
- npm run test:ci
# - npm run coveralls # Code coverage report
before_deploy:
- npm install -g firebase-tools
- echo 'About to deploy live...'
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
    tags: true
  token:
    secure: Id3Dqxwuh0NlPSdxb/FN+r6DF9rFnyWM+KiSc9GpRjUJbvUl9cHalQe+qbA4IkY80f7v5q8bhazu5R27Q6eQ7LkAo4+Ckm0/1IOz99NkTQhRZ0oRDvGdsuiwaWKy8a9/h7rjdoRuY83fnisPujcfoQbPZ9E5P4yRqohjbdw1TGmk+yYcUFXGebh0JAvXi5qh9J5+uOaAluwbj8tX1hX9+fcj2g5NXcZL6A+82VMijSCKWCkhi0icvum+/uaAT2Ei8as7ehFrHmmZtW0DPLX4az02y2Z6mYIWjOMLYBMUM0wOa+10jC9ZgcvhXfNbQnjBy0gSmBKxJjmfTz6Hym58dTzuqOzOKJjIFYpQo65g4wsUecfivK6HVHQd3xdAxvWfSD3cA0mofhn+icGV30MH2DZB3RH8ZHDLtgcR3sqh+1DOZamd3uJH4fCXM9S5L7eeHcQQoRQaD26ACV2cgdsxwAVge6JQGEV9wN6ki8SLq3HOGcYwdNHwuTVaby3wJDMcLhxtfL5DLMWzFlFqahOaBGznNCdbRH0fVzD8u/sJYERj8pGXe8Ibeey6bU/25eFUcI634oshRwoRBGOar0K6MD64/yfxijXuRaDCs3/VH76qyJxUfTiYVB1777KCTiWFiYJnXLDKQf6EZ9cZylhN5PHepmb6ZuakvgtYiMZvF9g=
  project: rock-paper-scissors-pwa
