language: node_js
node_js:
- '7'
notifications:
  email: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- sleep 1
before_script:
- npm rebuild phantomjs-prebuilt node-sass
- sleep 1
script:
- npm run lint
- npm run test:ci
before_deploy:
- npm install -g firebase-tools
- echo 'About to deploy live...'
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
    tags: true
  token:
    secure: TRChT3tb6wt6WgdyPYfNPeZZJzC6N4kNwNQ3P1Bo304KAvibkLgXG/RTodS3UL+B1qzL5axvD4hx+SdOZhYxOYUl72C3D/Np/eYNBYnG16CsUYGFyh8GnNkHGGrrcGhT6OmZOME44L3PH4/Hmse6AuZ4+Kmz0bL0LrRarY85k+3tVdKcN/RXltcW+S88EZ4aldqH/IBimOD3PDTOtO2K+Rpc2pBhMaQg8vvupQ6jYBvkf1dNGdOPTBw2FJcdwjvXJc93rl3wIPcCivIseo1CnAlMe3tEQrVsNbouwKa46v/eEshC74mVhmJrRYz1Im9/3NWiXfBaJS3ibGDV7tZbt/wOyr1Gb6v/1dM3m77xl2T62NvY2HOpSIZmYdQI1+AGSbwxLYU6Ho+jeADfOYtznlWGO4yL+h3tkNX0F5AEWlprlwrLKGaufzbO5mqHLbZ8X6Nsc1bQzcqMRd1M/pAuUp8W2f+k5TjnRqrTwvYR7pMBm4srVOlFEMiFAR+ghPvedDnF5kxjPPHT/TlrXTrlu6s5TDSRwK1WifFob1x5UcCA6FUlosysfutnZHbILYSeKR6Tttpkg/48ur5jJRzQqs2cvJheYcmBqPrq6oLLbyvreQhuNYbxyWCEj+f8uM3ARBo64rwyFA6p6AXdVIg7gFsE6srhVKxCSyOV4DoL31g=
  project: rock-paper-scissors-pwa
